ADC_CONVST	Location	PIN_Y21	Yes			
ADC_SCLK	Location	PIN_W24	Yes			
ADC_SDI	Location	PIN_W22	Yes			
ADC_SDO	Location	PIN_V23	Yes			
AUD_ADCDAT	Location	PIN_AJ29	Yes			
AUD_ADCLRCK	Location	PIN_AH29	Yes			
AUD_BCLK	Location	PIN_AF30	Yes			
AUD_DACDAT	Location	PIN_AF29	Yes			
AUD_DACLRCK	Location	PIN_AG30	Yes			
AUD_XCK	Location	PIN_AH30	Yes			
CLOCK_50	Location	PIN_AF14	Yes			
CLOCK2_50	Location	PIN_AA16	Yes			
CLOCK3_50	Location	PIN_Y26	Yes			
CLOCK4_50	Location	PIN_K14	Yes			
DRAM_ADDR[0]	Location	PIN_AK14	Yes			
DRAM_ADDR[1]	Location	PIN_AH14	Yes			
DRAM_ADDR[2]	Location	PIN_AG15	Yes			
DRAM_ADDR[3]	Location	PIN_AE14	Yes			
p	Location	PIN_AB15	Yes			
DRAM_ADDR[5]	Location	PIN_AC14	Yes			
DRAM_ADDR[6]	Location	PIN_AD14	Yes			
DRAM_ADDR[7]	Location	PIN_AF15	Yes			
DRAM_ADDR[8]	Location	PIN_AH15	Yes			
DRAM_ADDR[9]	Location	PIN_AG13	Yes			
DRAM_ADDR[10]	Location	PIN_AG12	Yes			
DRAM_ADDR[11]	Location	PIN_AH13	Yes			
DRAM_ADDR[12]	Location	PIN_AJ14	Yes			
DRAM_BA[0]	Location	PIN_AF13	Yes			
DRAM_BA[1]	Location	PIN_AJ12	Yes			
DRAM_CAS_N	Location	PIN_AF11	Yes			
DRAM_CKE	Location	PIN_AK13	Yes			
DRAM_CLK	Location	PIN_AH12	Yes			
DRAM_CS_N	Location	PIN_AG11	Yes			
DRAM_DQ[0]	Location	PIN_AK6	Yes			
DRAM_DQ[1]	Location	PIN_AJ7	Yes			
DRAM_DQ[2]	Location	PIN_AK7	Yes			
DRAM_DQ[3]	Location	PIN_AK8	Yes			
DRAM_DQ[4]	Location	PIN_AK9	Yes			
DRAM_DQ[5]	Location	PIN_AG10	Yes			
DRAM_DQ[6]	Location	PIN_AK11	Yes			
DRAM_DQ[7]	Location	PIN_AJ11	Yes			
DRAM_DQ[8]	Location	PIN_AH10	Yes			
DRAM_DQ[9]	Location	PIN_AJ10	Yes			
DRAM_DQ[10]	Location	PIN_AJ9	Yes			
DRAM_DQ[11]	Location	PIN_AH9	Yes			
DRAM_DQ[12]	Location	PIN_AH8	Yes			
DRAM_DQ[13]	Location	PIN_AH7	Yes			
DRAM_DQ[14]	Location	PIN_AJ6	Yes			
DRAM_DQ[15]	Location	PIN_AJ5	Yes			
DRAM_LDQM	Location	PIN_AB13	Yes			
DRAM_RAS_N	Location	PIN_AE13	Yes			
DRAM_UDQM	Location	PIN_AK12	Yes			
DRAM_WE_N	Location	PIN_AA13	Yes			
FPGA_I2C_SCLK	Location	PIN_Y24	Yes			
FPGA_I2C_SDAT	Location	PIN_Y23	Yes			
GPIO[0]	Location	PIN_W15	Yes			
GPIO[1]	Location	PIN_AK2	Yes			
GPIO[2]	Location	PIN_Y16	Yes			
GPIO[3]	Location	PIN_AK3	Yes			
GPIO[4]	Location	PIN_AJ1	Yes			
GPIO[5]	Location	PIN_AJ2	Yes			
GPIO[6]	Location	PIN_AH2	Yes			
GPIO[7]	Location	PIN_AH3	Yes			
GPIO[8]	Location	PIN_AH4	Yes			
GPIO[9]	Location	PIN_AH5	Yes			
GPIO[10]	Location	PIN_AG1	Yes			
GPIO[11]	Location	PIN_AG2	Yes			
GPIO[12]	Location	PIN_AG3	Yes			
GPIO[13]	Location	PIN_AG5	Yes			
GPIO[14]	Location	PIN_AG6	Yes			
GPIO[15]	Location	PIN_AG7	Yes			
GPIO[16]	Location	PIN_AG8	Yes			
GPIO[17]	Location	PIN_AF4	Yes			
GPIO[18]	Location	PIN_AF5	Yes			
GPIO[19]	Location	PIN_AF6	Yes			
GPIO[20]	Location	PIN_AF8	Yes			
GPIO[21]	Location	PIN_AF9	Yes			
GPIO[22]	Location	PIN_AF10	Yes			
GPIO[23]	Location	PIN_AE7	Yes			
GPIO[24]	Location	PIN_AE9	Yes			
GPIO[25]	Location	PIN_AE11	Yes			
GPIO[26]	Location	PIN_AE12	Yes			
GPIO[27]	Location	PIN_AD7	Yes			
GPIO[28]	Location	PIN_AD9	Yes			
GPIO[29]	Location	PIN_AD10	Yes			
GPIO[30]	Location	PIN_AD11	Yes			
GPIO[31]	Location	PIN_AD12	Yes			
GPIO[32]	Location	PIN_AC9	Yes			
GPIO[33]	Location	PIN_AC12	Yes			
GPIO[34]	Location	PIN_AB12	Yes			
GPIO[35]	Location	PIN_AA12	Yes			
HEX0[0]	Location	PIN_W17	Yes			
HEX0[1]	Location	PIN_V18	Yes			
HEX0[2]	Location	PIN_AG17	Yes			
HEX0[3]	Location	PIN_AG16	Yes			
HEX0[4]	Location	PIN_AH17	Yes			
HEX0[5]	Location	PIN_AG18	Yes			
HEX0[6]	Location	PIN_AH18	Yes			
HEX1[0]	Location	PIN_AF16	Yes			
HEX1[1]	Location	PIN_V16	Yes			
HEX1[2]	Location	PIN_AE16	Yes			
HEX1[3]	Location	PIN_AD17	Yes			
HEX1[4]	Location	PIN_AE18	Yes			
HEX1[5]	Location	PIN_AE17	Yes			
HEX1[6]	Location	PIN_V17	Yes			
HEX2[0]	Location	PIN_AA21	Yes			
HEX2[1]	Location	PIN_AB17	Yes			
HEX2[2]	Location	PIN_AA18	Yes			
HEX2[3]	Location	PIN_Y17	Yes			
HEX2[4]	Location	PIN_Y18	Yes			
HEX2[5]	Location	PIN_AF18	Yes			
HEX2[6]	Location	PIN_W16	Yes			
HEX3[0]	Location	PIN_Y19	Yes			
HEX3[1]	Location	PIN_W19	Yes			
HEX3[2]	Location	PIN_AD19	Yes			
HEX3[3]	Location	PIN_AA20	Yes			
HEX3[4]	Location	PIN_AC20	Yes			
HEX3[5]	Location	PIN_AA19	Yes			
HEX3[6]	Location	PIN_AD20	Yes			
HEX4[0]	Location	PIN_AD21	Yes			
HEX4[1]	Location	PIN_AG22	Yes			
HEX4[2]	Location	PIN_AE22	Yes			
HEX4[3]	Location	PIN_AE23	Yes			
HEX4[4]	Location	PIN_AG23	Yes			
HEX4[5]	Location	PIN_AF23	Yes			
HEX4[6]	Location	PIN_AH22	Yes			
HEX5[0]	Location	PIN_AF21	Yes			
HEX5[1]	Location	PIN_AG21	Yes			
HEX5[2]	Location	PIN_AF20	Yes			
HEX5[3]	Location	PIN_AG20	Yes			
HEX5[4]	Location	PIN_AE19	Yes			
HEX5[5]	Location	PIN_AF19	Yes			
HEX5[6]	Location	PIN_AB21	Yes			
HSMC_CLKIN_P1	Location	PIN_AA26	Yes			
HSMC_CLKIN_N1	Location	PIN_AB27	Yes			
HSMC_CLKIN_P2	Location	PIN_H15	Yes			
HSMC_CLKIN_N2	Location	PIN_G15	Yes			
HSMC_CLKIN0	Location	PIN_J14	Yes			
HSMC_CLKOUT_P1	Location	PIN_E7	Yes			
HSMC_CLKOUT_N1	Location	PIN_E6	Yes			
HSMC_CLKOUT_P2	Location	PIN_A11	Yes			
HSMC_CLKOUT_N2	Location	PIN_A10	Yes			
HSMC_CLKOUT0	Location	PIN_AD29	Yes			
HSMC_D[0]	Location	PIN_C10	Yes			
HSMC_D[1]	Location	PIN_H13	Yes			
HSMC_D[2]	Location	PIN_C9	Yes			
HSMC_D[3]	Location	PIN_H12	Yes			
HSMC_RX_D_P[0]	Location	PIN_G12	Yes			
HSMC_RX_D_P[1]	Location	PIN_K12	Yes			
HSMC_RX_D_P[2]	Location	PIN_G10	Yes			
HSMC_RX_D_P[3]	Location	PIN_J10	Yes			
HSMC_RX_D_P[4]	Location	PIN_K7	Yes			
HSMC_RX_D_P[5]	Location	PIN_J7	Yes			
HSMC_RX_D_P[6]	Location	PIN_H8	Yes			
HSMC_RX_D_P[7]	Location	PIN_F9	Yes			
HSMC_RX_D_P[8]	Location	PIN_F11	Yes			
HSMC_RX_D_P[9]	Location	PIN_B6	Yes			
HSMC_RX_D_P[10]	Location	PIN_E9	Yes			
HSMC_RX_D_P[11]	Location	PIN_E12	Yes			
HSMC_RX_D_P[12]	Location	PIN_D11	Yes			
HSMC_RX_D_P[13]	Location	PIN_C13	Yes			
HSMC_RX_D_P[14]	Location	PIN_F13	Yes			
HSMC_RX_D_P[15]	Location	PIN_H14	Yes			
HSMC_RX_D_P[16]	Location	PIN_F15	Yes			
HSMC_RX_D_N[0]	Location	PIN_G11	Yes			
HSMC_RX_D_N[1]	Location	PIN_J12	Yes			
HSMC_RX_D_N[2]	Location	PIN_F10	Yes			
HSMC_RX_D_N[3]	Location	PIN_J9	Yes			
HSMC_RX_D_N[4]	Location	PIN_K8	Yes			
HSMC_RX_D_N[5]	Location	PIN_H7	Yes			
HSMC_RX_D_N[6]	Location	PIN_G8	Yes			
HSMC_RX_D_N[7]	Location	PIN_F8	Yes			
HSMC_RX_D_N[8]	Location	PIN_E11	Yes			
HSMC_RX_D_N[9]	Location	PIN_B5	Yes			
HSMC_RX_D_N[10]	Location	PIN_D9	Yes			
HSMC_RX_D_N[11]	Location	PIN_D12	Yes			
HSMC_RX_D_N[12]	Location	PIN_D10	Yes			
HSMC_RX_D_N[13]	Location	PIN_B12	Yes			
HSMC_RX_D_N[14]	Location	PIN_E13	Yes			
HSMC_RX_D_N[15]	Location	PIN_G13	Yes			
HSMC_RX_D_N[16]	Location	PIN_F14	Yes			
HSMC_TX_D_P[0]	Location	PIN_A9	Yes			
HSMC_TX_D_P[1]	Location	PIN_E8	Yes			
HSMC_TX_D_P[2]	Location	PIN_G7	Yes			
HSMC_TX_D_P[3]	Location	PIN_D6	Yes			
HSMC_TX_D_P[4]	Location	PIN_D5	Yes			
HSMC_TX_D_P[5]	Location	PIN_E3	Yes			
HSMC_TX_D_P[6]	Location	PIN_E4	Yes			
HSMC_TX_D_P[7]	Location	PIN_C3	Yes			
HSMC_TX_D_P[8]	Location	PIN_E1	Yes			
HSMC_TX_D_P[9]	Location	PIN_D2	Yes			
HSMC_TX_D_P[10]	Location	PIN_B2	Yes			
HSMC_TX_D_P[11]	Location	PIN_A4	Yes			
HSMC_TX_D_P[12]	Location	PIN_A6	Yes			
HSMC_TX_D_P[13]	Location	PIN_C7	Yes			
HSMC_TX_D_P[14]	Location	PIN_C8	Yes			
HSMC_TX_D_P[15]	Location	PIN_C12	Yes			
HSMC_TX_D_P[16]	Location	PIN_B13	Yes			
HSMC_TX_D_N[0]	Location	PIN_A8	Yes			
HSMC_TX_D_N[1]	Location	PIN_D7	Yes			
HSMC_TX_D_N[2]	Location	PIN_F6	Yes			
HSMC_TX_D_N[3]	Location	PIN_C5	Yes			
HSMC_TX_D_N[4]	Location	PIN_C4	Yes			
HSMC_TX_D_N[5]	Location	PIN_E2	Yes			
HSMC_TX_D_N[6]	Location	PIN_D4	Yes			
HSMC_TX_D_N[7]	Location	PIN_B3	Yes			
HSMC_TX_D_N[8]	Location	PIN_D1	Yes			
HSMC_TX_D_N[9]	Location	PIN_C2	Yes			
HSMC_TX_D_N[10]	Location	PIN_B1	Yes			
HSMC_TX_D_N[11]	Location	PIN_A3	Yes			
HSMC_TX_D_N[12]	Location	PIN_A5	Yes			
HSMC_TX_D_N[13]	Location	PIN_B7	Yes			
HSMC_TX_D_N[14]	Location	PIN_B8	Yes			
HSMC_TX_D_N[15]	Location	PIN_B11	Yes			
HSMC_TX_D_N[16]	Location	PIN_A13	Yes			
HSMC_SCL	Location	PIN_AA28	Yes			
HSMC_SDA	Location	PIN_AE29	Yes			
IRDA_RXD	Location	PIN_W20	Yes			
IRDA_TXD	Location	PIN_W21	Yes			
KEY[0]	Location	PIN_AJ4	Yes			
KEY[1]	Location	PIN_AK4	Yes			
KEY[2]	Location	PIN_AA14	Yes			
KEY[3]	Location	PIN_AA15	Yes			
LEDR[0]	Location	PIN_AA24	Yes			
LEDR[1]	Location	PIN_AB23	Yes			
LEDR[2]	Location	PIN_AC23	Yes			
LEDR[3]	Location	PIN_AD24	Yes			
LEDR[4]	Location	PIN_AG25	Yes			
LEDR[5]	Location	PIN_AF25	Yes			
LEDR[6]	Location	PIN_AE24	Yes			
LEDR[7]	Location	PIN_AF24	Yes			
LEDR[8]	Location	PIN_AB22	Yes			
LEDR[9]	Location	PIN_AC22	Yes			
PS2_CLK	Location	PIN_AB25	Yes			
PS2_DAT	Location	PIN_AA25	Yes			
PS2_CLK2	Location	PIN_AC25	Yes			
PS2_DAT2	Location	PIN_AB26	Yes			
SW[0]	Location	PIN_AB30	Yes			
SW[1]	Location	PIN_Y27	Yes			
SW[2]	Location	PIN_AB28	Yes			
SW[3]	Location	PIN_AC30	Yes			
SW[4]	Location	PIN_W25	Yes			
SW[5]	Location	PIN_V25	Yes			
SW[6]	Location	PIN_AC28	Yes			
SW[7]	Location	PIN_AD30	Yes			
SW[8]	Location	PIN_AC29	Yes			
SW[9]	Location	PIN_AA30	Yes			
TD_CLK27	Location	PIN_AC18	Yes			
TD_DATA[0]	Location	PIN_AG27	Yes			
TD_DATA[1]	Location	PIN_AF28	Yes			
TD_DATA[2]	Location	PIN_AE28	Yes			
TD_DATA[3]	Location	PIN_AE27	Yes			
TD_DATA[4]	Location	PIN_AE26	Yes			
TD_DATA[5]	Location	PIN_AD27	Yes			
TD_DATA[6]	Location	PIN_AD26	Yes			
TD_DATA[7]	Location	PIN_AD25	Yes			
TD_HS	Location	PIN_AH28	Yes			
TD_RESET_N	Location	PIN_AC27	Yes			
TD_VS	Location	PIN_AG28	Yes			
VGA_B[0]	Location	PIN_AJ21	Yes			
VGA_B[1]	Location	PIN_AJ20	Yes			
VGA_B[2]	Location	PIN_AH20	Yes			
VGA_B[3]	Location	PIN_AJ19	Yes			
VGA_B[4]	Location	PIN_AH19	Yes			
VGA_B[5]	Location	PIN_AJ17	Yes			
VGA_B[6]	Location	PIN_AJ16	Yes			
VGA_B[7]	Location	PIN_AK16	Yes			
VGA_BLANK_N	Location	PIN_AK22	Yes			
VGA_CLK	Location	PIN_AK21	Yes			
VGA_G[0]	Location	PIN_AK26	Yes			
VGA_G[1]	Location	PIN_AJ25	Yes			
VGA_G[2]	Location	PIN_AH25	Yes			
VGA_G[3]	Location	PIN_AK24	Yes			
VGA_G[4]	Location	PIN_AJ24	Yes			
VGA_G[5]	Location	PIN_AH24	Yes			
VGA_G[6]	Location	PIN_AK23	Yes			
VGA_G[7]	Location	PIN_AH23	Yes			
VGA_HS	Location	PIN_AK19	Yes			
VGA_R[0]	Location	PIN_AK29	Yes			
VGA_R[1]	Location	PIN_AK28	Yes			
VGA_R[2]	Location	PIN_AK27	Yes			
VGA_R[3]	Location	PIN_AJ27	Yes			
VGA_R[4]	Location	PIN_AH27	Yes			
VGA_R[5]	Location	PIN_AF26	Yes			
VGA_R[6]	Location	PIN_AG26	Yes			
VGA_R[7]	Location	PIN_AJ26	Yes			
VGA_SYNC_N	Location	PIN_AJ22	Yes			
VGA_VS	Location	PIN_AK18	Yes			
HPS_CONV_USB_N	Location	PIN_B15	Yes			
HPS_DDR3_ADDR[0]	Location	PIN_F26	Yes			
HPS_DDR3_ADDR[1]	Location	PIN_G30	Yes			
HPS_DDR3_ADDR[2]	Location	PIN_F28	Yes			
HPS_DDR3_ADDR[3]	Location	PIN_F30	Yes			
HPS_DDR3_ADDR[4]	Location	PIN_J25	Yes			
HPS_DDR3_ADDR[5]	Location	PIN_J27	Yes			
HPS_DDR3_ADDR[6]	Location	PIN_F29	Yes			
HPS_DDR3_ADDR[7]	Location	PIN_E28	Yes			
HPS_DDR3_ADDR[8]	Location	PIN_H27	Yes			
HPS_DDR3_ADDR[9]	Location	PIN_G26	Yes			
HPS_DDR3_ADDR[10]	Location	PIN_D29	Yes			
HPS_DDR3_ADDR[11]	Location	PIN_C30	Yes			
HPS_DDR3_ADDR[12]	Location	PIN_B30	Yes			
HPS_DDR3_ADDR[13]	Location	PIN_C29	Yes			
HPS_DDR3_ADDR[14]	Location	PIN_H25	Yes			
HPS_DDR3_BA[0]	Location	PIN_E29	Yes			
HPS_DDR3_BA[1]	Location	PIN_J24	Yes			
HPS_DDR3_BA[2]	Location	PIN_J23	Yes			
HPS_DDR3_CAS_N	Location	PIN_E27	Yes			
HPS_DDR3_CKE	Location	PIN_L29	Yes			
HPS_DDR3_CK_N	Location	PIN_L23	Yes			
HPS_DDR3_CK_P	Location	PIN_M23	Yes			
HPS_DDR3_CS_N	Location	PIN_H24	Yes			
HPS_DDR3_DM[0]	Location	PIN_K28	Yes			
HPS_DDR3_DM[1]	Location	PIN_M28	Yes			
HPS_DDR3_DM[2]	Location	PIN_R28	Yes			
HPS_DDR3_DM[3]	Location	PIN_W30	Yes			
HPS_DDR3_DQ[0]	Location	PIN_K23	Yes			
HPS_DDR3_DQ[1]	Location	PIN_K22	Yes			
HPS_DDR3_DQ[2]	Location	PIN_H30	Yes			
HPS_DDR3_DQ[3]	Location	PIN_G28	Yes			
HPS_DDR3_DQ[4]	Location	PIN_L25	Yes			
HPS_DDR3_DQ[5]	Location	PIN_L24	Yes			
HPS_DDR3_DQ[6]	Location	PIN_J30	Yes			
HPS_DDR3_DQ[7]	Location	PIN_J29	Yes			
HPS_DDR3_DQ[8]	Location	PIN_K26	Yes			
HPS_DDR3_DQ[9]	Location	PIN_L26	Yes			
HPS_DDR3_DQ[10]	Location	PIN_K29	Yes			
HPS_DDR3_DQ[11]	Location	PIN_K27	Yes			
HPS_DDR3_DQ[12]	Location	PIN_M26	Yes			
HPS_DDR3_DQ[13]	Location	PIN_M27	Yes			
HPS_DDR3_DQ[14]	Location	PIN_L28	Yes			
HPS_DDR3_DQ[15]	Location	PIN_M30	Yes			
HPS_DDR3_DQ[16]	Location	PIN_U26	Yes			
HPS_DDR3_DQ[17]	Location	PIN_T26	Yes			
HPS_DDR3_DQ[18]	Location	PIN_N29	Yes			
HPS_DDR3_DQ[19]	Location	PIN_N28	Yes			
HPS_DDR3_DQ[20]	Location	PIN_P26	Yes			
HPS_DDR3_DQ[21]	Location	PIN_P27	Yes			
HPS_DDR3_DQ[22]	Location	PIN_N27	Yes			
HPS_DDR3_DQ[23]	Location	PIN_R29	Yes			
HPS_DDR3_DQ[24]	Location	PIN_P24	Yes			
HPS_DDR3_DQ[25]	Location	PIN_P25	Yes			
HPS_DDR3_DQ[26]	Location	PIN_T29	Yes			
HPS_DDR3_DQ[27]	Location	PIN_T28	Yes			
HPS_DDR3_DQ[28]	Location	PIN_R27	Yes			
HPS_DDR3_DQ[29]	Location	PIN_R26	Yes			
HPS_DDR3_DQ[30]	Location	PIN_V30	Yes			
HPS_DDR3_DQ[31]	Location	PIN_W29	Yes			
HPS_DDR3_DQS_N[0]	Location	PIN_M19	Yes			
HPS_DDR3_DQS_N[1]	Location	PIN_N24	Yes			
HPS_DDR3_DQS_N[2]	Location	PIN_R18	Yes			
HPS_DDR3_DQS_N[3]	Location	PIN_R21	Yes			
HPS_DDR3_DQS_P[0]	Location	PIN_N18	Yes			
HPS_DDR3_DQS_P[1]	Location	PIN_N25	Yes			
HPS_DDR3_DQS_P[2]	Location	PIN_R19	Yes			
HPS_DDR3_DQS_P[3]	Location	PIN_R22	Yes			
HPS_DDR3_ODT	Location	PIN_H28	Yes			
HPS_DDR3_RAS_N	Location	PIN_D30	Yes			
HPS_DDR3_RESET_N	Location	PIN_P30	Yes			
HPS_DDR3_RZQ	Location	PIN_D27	Yes			
HPS_DDR3_WE_N	Location	PIN_C28	Yes			
HPS_ENET_GTX_CLK	Location	PIN_H19	Yes			
HPS_ENET_INT_N	Location	PIN_C19	Yes			
HPS_ENET_MDC	Location	PIN_B21	Yes			
HPS_ENET_MDIO	Location	PIN_E21	Yes			
HPS_ENET_RX_CLK	Location	PIN_G20	Yes			
HPS_ENET_RX_DATA[0]	Location	PIN_A21	Yes			
HPS_ENET_RX_DATA[1]	Location	PIN_B20	Yes			
HPS_ENET_RX_DATA[2]	Location	PIN_B18	Yes			
HPS_ENET_RX_DATA[3]	Location	PIN_D21	Yes			
HPS_ENET_RX_DV	Location	PIN_K17	Yes			
HPS_ENET_TX_DATA[0]	Location	PIN_F20	Yes			
HPS_ENET_TX_DATA[1]	Location	PIN_J19	Yes			
HPS_ENET_TX_DATA[2]	Location	PIN_F21	Yes			
HPS_ENET_TX_DATA[3]	Location	PIN_F19	Yes			
HPS_ENET_TX_EN	Location	PIN_A20	Yes			
HPS_FLASH_DATA[0]	Location	PIN_C20	Yes			
HPS_FLASH_DATA[1]	Location	PIN_H18	Yes			
HPS_FLASH_DATA[2]	Location	PIN_A19	Yes			
HPS_FLASH_DATA[3]	Location	PIN_E19	Yes			
HPS_FLASH_DCLK	Location	PIN_D19	Yes			
HPS_FLASH_NCSO	Location	PIN_A18	Yes			
HPS_GSENSOR_INT	Location	PIN_B22	Yes			
HPS_I2C1_SCLK	Location	PIN_E23	Yes			
HPS_I2C1_SDAT	Location	PIN_C24	Yes			
HPS_I2C2_SCLK	Location	PIN_H23	Yes			
HPS_I2C2_SDAT	Location	PIN_A25	Yes			
HPS_I2C_CONTROL	Location	PIN_B26	Yes			
HPS_KEY	Location	PIN_G21	Yes			
HPS_LCM_BK	Location	PIN_B17	Yes			
HPS_LCM_D_C	Location	PIN_C18	Yes			
HPS_LCM_RST_N	Location	PIN_E17	Yes			
HPS_LCM_SPIM_CLK	Location	PIN_A23	Yes			
HPS_LCM_SPIM_MOSI	Location	PIN_C22	Yes			
HPS_LCM_SPIM_SS	Location	PIN_H20	Yes			
HPS_LED	Location	PIN_A24	Yes			
HPS_LTC_GPIO	Location	PIN_H17	Yes			
HPS_RESET_N	Location	PIN_F23	Yes			
HPS_SD_CLK	Location	PIN_A16	Yes			
HPS_SD_CMD	Location	PIN_F18	Yes			
HPS_SD_DATA[0]	Location	PIN_G18	Yes			
HPS_SD_DATA[1]	Location	PIN_C17	Yes			
HPS_SD_DATA[2]	Location	PIN_D17	Yes			
HPS_SD_DATA[3]	Location	PIN_B16	Yes			
HPS_SPIM_CLK	Location	PIN_C23	Yes			
HPS_SPIM_MISO	Location	PIN_E24	Yes			
HPS_SPIM_MOSI	Location	PIN_D22	Yes			
HPS_SPIM_SS	Location	PIN_D24	Yes			
HPS_UART_RX	Location	PIN_B25	Yes			
HPS_UART_TX	Location	PIN_C25	Yes			
HPS_USB_CLKOUT	Location	PIN_N16	Yes			
HPS_USB_DATA[0]	Location	PIN_E16	Yes			
HPS_USB_DATA[1]	Location	PIN_G16	Yes			
HPS_USB_DATA[2]	Location	PIN_D16	Yes			
HPS_USB_DATA[3]	Location	PIN_D14	Yes			
HPS_USB_DATA[4]	Location	PIN_A15	Yes			
HPS_USB_DATA[5]	Location	PIN_C14	Yes			
HPS_USB_DATA[6]	Location	PIN_D15	Yes			
HPS_USB_DATA[7]	Location	PIN_M17	Yes			
HPS_USB_DIR	Location	PIN_E14	Yes			
HPS_USB_NXT	Location	PIN_A14	Yes			
HPS_USB_STP	Location	PIN_C15	Yes			